[project]
name = "excel-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.5.0",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
]
